//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Hastane_Otomasyon_Cihan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Hasta_Yatis
    {
        [Required(ErrorMessage ="Id Boþ olamaz")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Yatýþ tarihi boþ olamaz")]
        public System.DateTime yat_tarihi { get; set; }
        
        public Nullable<System.DateTime> cik_tarihi { get; set; }
        [Required(ErrorMessage = "Oda no boþ olamaz")]
        public int oda_no { get; set; }
        [Required(ErrorMessage = "Hasta no Seçmek zorunlu")]
        public int Hasta_no { get; set; }
        [Required(ErrorMessage = "Doktor no Seçmek zorunlu")]
        public int Doktor_no { get; set; }
        [Required(ErrorMessage = "Bölüm no Seçmek zorunlu")]
        public int Dept_no { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual Hastalar Hastalar { get; set; }
    }
}
